[[intro]]
== Introduction

The Rivos custom vendor extensions exist to supplement the standard RISC-V extension ecosystem.

=== Overview of Extensions

The document currently describes the following extensions:

* <<xrivosvizip,Vector Register Zips (XRivosVizip)>>
* <<xrivosvisni,Vector Integer Small New Instructions (XRivosVisni)>>

=== Assembly mnemonic and extension naming conventions

Rivos uses the "ri." prefix for the vendor specific prefix.  A previous version of this document had used "rv.", but this was changed before any extension left Experimental status.

For extension naming, Rivos follows the "X" + "Vendor" + "Extension Name" scheme.  The names which would result from the alternate "X" + "Vendor Prefix" + "Extension Name" scheme are explicitly reserved.  For example, the vector register zips extension is named XRivosVizip, not XRiVizip.

Please see https://github.com/riscv-non-isa/riscv-toolchain-conventions for context.

=== Life Cycle of an Extension

The lifecycle of each extension is defined on a per-extension basis and can be found in the relevant sub-section.

The possible states are:

* Experimental - Extension specification is an early draft.  Everything may change.
* Stable - Encodings and functionality will not change.  Clarifications may be made as needed.

